name = "aiken-lang/fuzz"
version = "main"
compiler = "v1.1.0"
plutus = "v3"
license = "Apache-2.0"
description = "A library for writing Aiken's fuzzers."

[repository]
user = "aiken-lang"
project = "fuzz"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2"
source = "github"

[config]
